# This file was generated by GoReleaser. DO NOT EDIT.
cask "atl" do
  postflight_steps do
    if_path_exists "/usr/bin/xattr" do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/atl"]
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "0937769aaa414cec44b96e6144963bf59cbf26e33000ae2536f82c65aa927b01"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c25a675e40324c962f2059175b8fc9638cbb4604be9ec1e35eff91d2eb81703"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "03ac8ae1fe8d20c9e1c286b4ed0a577c80174a7eb8d9f69f104ff81b7ba9d871"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e7656261648c3f2746c112c7e72a91a33d43f5878fbf40d7509c3b372cd6373"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "atl"
  desc "Command-line interface for Atlassian Cloud (Jira + Confluence)"
  homepage "https://github.com/branow/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atl"

  # No zap stanza required
end
