# This file was generated by GoReleaser. DO NOT EDIT.
cask "atl" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "83b89d862a0c58a5035ba5cb7ff53bc1f7cca1ee36bf9d17cd1626b0cc427c76"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "58fa11c688b4b9f3ee14db9691448525005ce083dde0c53f92e6abc080bc554d"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "be1c1ca9553914fa7fb72d25907acfecb19c77e4c7efc529da39d284ab550920"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "da42882d655269cdd75d5c1f93153ac3874e43804157617d98f2e70f22d80ed1"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atl"
  desc "Command-line interface for Atlassian Cloud (Jira + Confluence)"
  homepage "https://github.com/branow/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atl"

  postflight do
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atl"]
    end
  end

  # No zap stanza required

end
