# This file was generated by GoReleaser. DO NOT EDIT.
cask "atl" do
  postflight_steps do
    if_path_exists "/usr/bin/xattr" do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/atl"]
    end
  end

  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "2fd7e4c8d82ef8aa184e5027501963e00c4cb863a23237a2f0f3da8dd2b5854e"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "068e6c780f58c9093324c5f41b5c2563eb84cc73b5aa409431c8ef62157cfbda"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e18019a744edad3955aabf175c17898ee6fd5b227d280b0bcaf27b4bc682f428"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "390597ab9a80686db4d4b434cf642ffb7add9e30c55491694fc09d5a0fa01b65"
      url "https://github.com/branow/atlassian-cli/releases/download/v#{version}/atl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "atl"
  desc "Command-line interface for Atlassian Cloud (Jira + Confluence)"
  homepage "https://github.com/branow/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atl"

  # No zap stanza required
end
