# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbmap" do
  postflight_steps do
    if_path_exists "/usr/bin/xattr" do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/dbmap"]
    end
  end

  version "0.1.0"

  on_macos do
    sha256 "77bf38acc41f8daaeb2514542510421062322db54cbad2096fa9d8ed840e0528"
    url "https://github.com/branow/dbmap/releases/download/v#{version}/dbmap_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "f88e450fcc1a6ff2270a3ab2e055cd9e15be7b6223f63fee52be576e92c2b1ee"
      url "https://github.com/branow/dbmap/releases/download/v#{version}/dbmap_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8cc98f2d8471164a2b40d1b3ec350568864fc3489f5455b594451a6a620da3eb"
      url "https://github.com/branow/dbmap/releases/download/v#{version}/dbmap_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dbmap"
  desc "Index a database into a compact map an agent can read in one pass"
  homepage "https://github.com/branow/dbmap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbmap"

  # No zap stanza required
end
