# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbmap" do
  postflight_steps do
    if_path_exists "/usr/bin/xattr" do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/dbmap"]
    end
  end

  version "0.2.1"

  on_macos do
    sha256 "c83ccd9ebe50d74bb502b99835ad14acbbedfd97b181420afc033b0e0b9e199c"
    url "https://github.com/branow/dbmap/releases/download/v#{version}/dbmap_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "40e1ac0087ab446e46e21f8e25ae07bf76bea8c8a6b55c5f6f8341e6533229c6"
      url "https://github.com/branow/dbmap/releases/download/v#{version}/dbmap_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b2cb046886db8d624578df8fd4fbb97c5ece8eabdb118b7b66207d5862bdeeca"
      url "https://github.com/branow/dbmap/releases/download/v#{version}/dbmap_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dbmap"
  desc "Index a database into a compact map an agent can read in one pass"
  homepage "https://github.com/branow/dbmap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbmap"

  # No zap stanza required
end
