# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbmap" do
  postflight_steps do
    if_path_exists "/usr/bin/xattr" do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/dbmap"]
    end
  end

  version "0.3.0"

  on_macos do
    sha256 "4ee362c70b5a677f1e804067ef303a989afa1a0a76f04d7b2c804e00825d4a65"
    url "https://github.com/branow/dbmap/releases/download/v#{version}/dbmap_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "e4932301a2223418c6f54c27cf014c250eeddd1beee9c34595d47df0936e1fb9"
      url "https://github.com/branow/dbmap/releases/download/v#{version}/dbmap_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "320b23117fbee48c0e0ea26b3b7f3e17871adef1d061e5a6ec844953654079d2"
      url "https://github.com/branow/dbmap/releases/download/v#{version}/dbmap_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dbmap"
  desc "Index a database into a compact map an agent can read in one pass"
  homepage "https://github.com/branow/dbmap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbmap"

  # No zap stanza required
end
