# This file was generated by GoReleaser. DO NOT EDIT.
cask "exigo" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "f8449f370521ad43fa3363503675ae357eb6fba9d4f5e828227a46b5a85b6d9f"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "abf49cf5f4d6378cd2960b1ebd6d1a78eb62089ebc033073d45898649e6fcb51"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce3cdda42ae88c571618b71c5ca9301872b7949c4f62db68d8e6e282e76d4b77"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4272315fdc14b7d058926fec04d0261711a4473baf899906033a79748be18255"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "exigo"
  desc "Command-line interface for the Exigo direct-selling back-office API"
  homepage "https://github.com/branow/exigo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "exigo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 1
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/exigo"]
    end
  end

  # No zap stanza required

end
