# This file was generated by GoReleaser. DO NOT EDIT.
cask "exigo" do
  postflight_steps do
    if_path_exists "/usr/bin/xattr" do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/exigo"]
    end
  end

  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "c6c50e6ead4b5336ed5b3df86843ab1b92b5f1b877826662b2647a6e367f8a2b"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a4664781d20b92c796451496c6cf033f93f2cc53094b3ec133c4ad312b94cba"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5f3519e463ad974adc5fac63c613b119e88afa0b8b7c77535469b94a3c04d551"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e9841c423568bfd8b40b34c4e19e2922b963d361f32163a8b7ba6e9f33e3de59"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "exigo"
  desc "Command-line interface for the Exigo direct-selling back-office API"
  homepage "https://github.com/branow/exigo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "exigo"

  # No zap stanza required
end
