# This file was generated by GoReleaser. DO NOT EDIT.
cask "exigo" do
  postflight_steps do
    if_path_exists "/usr/bin/xattr" do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/exigo"]
    end
  end

  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "45d2ea64150e963c7d4aea473ec9e36c85209eadcd648870afc01dacadbaf55c"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2cb3fe6810ecdc3c04a5344a37c17ea2022576841f9ad4d0a547627ae50a869b"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0dd3d08b0a4b0f02f0d6a5dd5823cb9b269aad5c9a816ba3267d6bc96067a9cb"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7399a66ef2c1044de2d9858fb5121f57f2e5ae9bc509b655509df46f084a2585"
      url "https://github.com/branow/exigo-cli/releases/download/v#{version}/exigo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "exigo"
  desc "Command-line interface for the Exigo direct-selling back-office API"
  homepage "https://github.com/branow/exigo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "exigo"

  # No zap stanza required
end
