# This file was generated by GoReleaser. DO NOT EDIT.
cask "figma" do
  postflight_steps do
    if_path_exists "/usr/bin/xattr" do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/figma"]
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "ce72ccd6df24f2c29f1fdb19ac4a899df78bffdeed9a47b568d96b1bbcb219b6"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "80c4bf5bed91751baec8793497b7d16e6d6e6da4db8cf02e41cb541947a633fe"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "761ce5505036423ae9a0fad25affb4fb0b5201d4fd06004c724d420147ce646c"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d933c074a22fbce89dcd00e4f6b981e60013a2bd8ff57540c3ed29a7db2546d0"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_linux_amd64.tar.gz"
    end
  end

  name "figma"
  desc "Command-line interface for the Figma REST API"
  homepage "https://github.com/branow/figma-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "figma"

  # No zap stanza required
end
