# This file was generated by GoReleaser. DO NOT EDIT.
cask "figma" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "9a9da90980bd97fcf1b0f0d29e31d58fc658be6e544e4602d715e4bc6acb27f5"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4180146e32c6966530edb7f3c078a0e45ef9f48cbcc20f73df81cda1b077572b"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b8c41495392e20f7c26d6b27ba72c6b43f4acf471d28384db9195cfbb721022b"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d073d60a2e9c8c84f30a08bbdf0c79035496303de496adef563d6b09927bfe3b"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_linux_amd64.tar.gz"
    end
  end

  name "figma"
  desc "Command-line interface for the Figma REST API"
  homepage "https://github.com/branow/figma-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "figma"

  postflight do
    if File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/figma"]
    end
  end

  # No zap stanza required
end
