# This file was generated by GoReleaser. DO NOT EDIT.
cask "figma-cli" do
  postflight_steps do
    if_path_exists "/usr/bin/xattr" do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/figma"]
    end
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "02b53703e7f628d877b3c23ad189a56ea046429a147c7ae55a8650835e57eaa5"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b4fa7d7d280e6dc86923eb4923b1b9be52c379c75d19c95f9102f846ec2ec6a9"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "266f97467392d5120afde36b9616906e5ec9be61b538f6235b66adece994b8ee"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7efc37d549a540092ef23b54993e01066fed14c0300bce48b5db53856a0c91c3"
      url "https://github.com/branow/figma-cli/releases/download/v#{version}/figma_#{version}_linux_amd64.tar.gz"
    end
  end

  name "figma-cli"
  desc "Command-line interface for the Figma REST API"
  homepage "https://github.com/branow/figma-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "figma"

  # No zap stanza required
end
